/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amator_telsiz;


import static amator_telsiz.menu.operator_ismi;
import static amator_telsiz.mysql_bilgileri.getConnection;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Erkin
 */
public class rehber extends javax.swing.JFrame {
  

    
    
    public rehber() {     
        initComponents();
        findUsers();
        this.setTitle("Rehber");
        
    }
    
    public ArrayList<rehber_class> ListUsers(String ValToSearch)
    {
        ArrayList<rehber_class> usersList = new ArrayList<rehber_class>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `"+operator_ismi.getText()+"` WHERE CONCAT(`callsign`) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            rehber_class user;
            
            while(rs.next())
            {
                user = new rehber_class(
                                
                                 rs.getString("Ad Soyad"),
                                 rs.getString("callsign"),
                                 rs.getString("telefon"),
                                 rs.getString("email"),
                                 rs.getString("QTH"),
                                 rs.getString("Kullandığı Cihazlar")
                                );
                usersList.add(user);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
     public void findUsers()
    {
        ArrayList<rehber_class> users = ListUsers(arama.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Ad Soyad","Çağrı İşareti","Telefon","e-Mail","QTH","Kullandığı Cihazlar"});
        Object[] row = new Object[6];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getAdSoyad();
            row[1] = users.get(i).getcallsign();
            row[2] = users.get(i).gettelefon();
            row[3] = users.get(i).getemail();
            row[4] = users.get(i).getQTH();
            row[5] = users.get(i).getKulCih();
            model.addRow(row);
        }
      rehber.setModel(model);
       
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        operator = new javax.swing.JTextField();
        J_operator = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        J_callsign = new javax.swing.JLabel();
        callsign = new javax.swing.JTextField();
        telefon = new javax.swing.JTextField();
        J_Telefon = new javax.swing.JLabel();
        J_Mail = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        J_QTH = new javax.swing.JLabel();
        qth = new javax.swing.JTextField();
        J_cihaz = new javax.swing.JLabel();
        cihaz_bil = new javax.swing.JTextField();
        buton_kayıt = new javax.swing.JButton();
        buton_güncelle = new javax.swing.JButton();
        buton_sil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rehber = new javax.swing.JTable();
        arama = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        JL_güncelle = new javax.swing.JLabel();
        JT_güncelle = new javax.swing.JTextField();
        JT_sil = new javax.swing.JTextField();
        JL_sil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jPanel2.setBackground(new java.awt.Color(231, 76, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rehber");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(513, 513, 513))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unnamed.png"))); // NOI18N
        jLabel2.setText("Ana Menü");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        J_operator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_operator.setForeground(new java.awt.Color(255, 255, 255));
        J_operator.setText("Operatör Adı :");

        J_callsign.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_callsign.setForeground(new java.awt.Color(255, 255, 255));
        J_callsign.setText("Çağrı İşareti :");

        callsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callsignActionPerformed(evt);
            }
        });

        J_Telefon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_Telefon.setForeground(new java.awt.Color(255, 255, 255));
        J_Telefon.setText("Telefon :");

        J_Mail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_Mail.setForeground(new java.awt.Color(255, 255, 255));
        J_Mail.setText("E-Mail :");

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });

        J_QTH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_QTH.setForeground(new java.awt.Color(255, 255, 255));
        J_QTH.setText("QTH :");

        J_cihaz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J_cihaz.setForeground(new java.awt.Color(255, 255, 255));
        J_cihaz.setText("Cihaz Bilgisi :");

        buton_kayıt.setText("Yeni Kayıt");
        buton_kayıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_kayıtActionPerformed(evt);
            }
        });

        buton_güncelle.setText("Güncelle");

        buton_sil.setText("Sil");
        buton_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_silActionPerformed(evt);
            }
        });

        rehber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(rehber);

        arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaActionPerformed(evt);
            }
        });
        arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Güncelleme/Silme İşlemleri");

        JL_güncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JL_güncelle.setForeground(new java.awt.Color(255, 255, 255));
        JL_güncelle.setText("Çağrı İşareti :");

        JL_sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JL_sil.setForeground(new java.awt.Color(255, 255, 255));
        JL_sil.setText("Çağrı İşareti :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ara :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("* Üstteki bilgileri doldurduktan sonra aşağıdaki bölüme");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("kişinin çağrı işaretini girip \"Güncelle\" butonuna basınız.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(J_callsign)
                                                        .addComponent(J_Telefon)
                                                        .addComponent(J_Mail)
                                                        .addComponent(J_QTH)
                                                        .addComponent(J_cihaz))
                                                    .addGap(23, 23, 23)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cihaz_bil, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                                            .addComponent(qth)
                                                            .addComponent(callsign)
                                                            .addComponent(mail))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(J_operator)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(62, 62, 62))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(buton_kayıt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(86, 86, 86)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JL_güncelle)
                                            .addComponent(JL_sil))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JT_güncelle)
                                                .addGap(18, 18, 18)
                                                .addComponent(buton_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JT_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buton_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_operator)
                            .addComponent(operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_callsign)
                            .addComponent(callsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J_Telefon))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_Mail)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_QTH)
                            .addComponent(qth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(J_cihaz)
                            .addComponent(cihaz_bil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buton_kayıt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buton_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_güncelle)
                            .addComponent(JT_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buton_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JL_sil)
                            .addComponent(JT_sil))
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        menu u1 =new menu();
        menu.operator_ismi.setText(giris.jTextField_Username.getText());
        u1.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void callsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callsignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callsignActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void buton_kayıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_kayıtActionPerformed
         String _operator = operator.getText();
         String _callsign = callsign.getText();  
         String _telefon = telefon.getText();
         String _mail = mail.getText();
         String _qth = qth.getText();
         String _cihbil = cihaz_bil.getText();
         

         
             if(!checkUsername(_callsign))
             {
                 PreparedStatement ps;
                 ResultSet rs;
                 String registerUserQuery = "INSERT INTO `"+operator_ismi.getText()+"`(`Ad Soyad`, `callsign`, `telefon`, `email`, `QTH`, `Kullandığı Cihazlar`) VALUES (?,?,?,?,?,?)";
                 
                 try {
                     
                     ps = mysql_bilgileri.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, _operator);
                     ps.setString(2, _callsign);
                     ps.setString(3, _telefon);
                     ps.setString(4, _mail);
                     ps.setString(5, _qth);
                     ps.setString(6, _cihbil);
                    
                     
                     
                         
                         if(ps.executeUpdate() != 0){
                             JOptionPane.showMessageDialog(null, "Hesabınız Başarıyla Oluşturuldu");
                         }else{
                             JOptionPane.showMessageDialog(null, "Lütfen Bilgilerinizi Kontrol Edin");
                         }
                         
                      
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(kayıt.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
                 
                findUsers(); 
         
    }//GEN-LAST:event_buton_kayıtActionPerformed

    private void aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaKeyReleased
    findUsers();        
    }//GEN-LAST:event_aramaKeyReleased

    private void aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aramaActionPerformed

    private void buton_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_silActionPerformed

    }//GEN-LAST:event_buton_silActionPerformed
 public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `"+operator_ismi.getText()+"` WHERE `callsign` = ?";
        
        try {
            
            st = mysql_bilgileri.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Eklemek istediğiniz çağrı işareti zaten rehberinizde kayıtlı", "Kayıt Hatası", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(kayıt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rehber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rehber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_güncelle;
    private javax.swing.JLabel JL_sil;
    private javax.swing.JTextField JT_güncelle;
    private javax.swing.JTextField JT_sil;
    private javax.swing.JLabel J_Mail;
    private javax.swing.JLabel J_QTH;
    private javax.swing.JLabel J_Telefon;
    private javax.swing.JLabel J_callsign;
    private javax.swing.JLabel J_cihaz;
    private javax.swing.JLabel J_operator;
    private javax.swing.JTextField arama;
    private javax.swing.JButton buton_güncelle;
    private javax.swing.JButton buton_kayıt;
    private javax.swing.JButton buton_sil;
    private javax.swing.JTextField callsign;
    private javax.swing.JTextField cihaz_bil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField operator;
    private javax.swing.JTextField qth;
    private javax.swing.JTable rehber;
    private javax.swing.JTextField telefon;
    // End of variables declaration//GEN-END:variables
}
