/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amator_telsiz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static amator_telsiz.mysql_bilgileri.getConnection;
/**
 *
 * @author Erkin
 */
public class role_listesi extends javax.swing.JFrame {
   ButtonGroup bg=new ButtonGroup();

    /**
     * Creates new form JTable_Search
     */
    public role_listesi() {
        initComponents();
        findUsers();
        addToGroup();
        this.setTitle("Amatör Röle Listesi");
    }
    private void addToGroup()
    {
        bg.add(aprs_radio);
        bg.add(uhf_radio);
        bg.add(vhf_radio);
        bg.add(echo_radio);
        bg.add(dmr_radio);
        bg.add(tümü_radio);
        
    }
    private String getSelected()
    {
        if(aprs_radio.isSelected())
        {
            return "APRS";
        }else if(uhf_radio.isSelected())
        {
            return "UHF";
        }else if(vhf_radio.isSelected())
        {
            return "VHF";
        }else if(dmr_radio.isSelected())
        {
            return "DMR";
        }else if(echo_radio.isSelected())
        {
            return "EchoLink";
        }else if(tümü_radio.isSelected())
        {
            return "Tümü";
        }else
        {
            return "Band";
        }
        
    }
   
    public ArrayList<kullanıcılar_class> ListUsers(String ValToSearch)
    {
        ArrayList<kullanıcılar_class> usersList = new ArrayList<kullanıcılar_class>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `role_listesi` WHERE CONCAT(`İl`) LIKE '%"+ValToSearch+"%' OR ";
            rs = st.executeQuery(searchQuery);
            
            kullanıcılar_class user;
            
            while(rs.next())
            {
                user = new kullanıcılar_class(
                                
                                 rs.getString("İl"),
                                 rs.getString("Yer"),
                                 rs.getString("Yükseklik"),
                                 rs.getString("Güç"),
                                 rs.getString("Band"),
                                 rs.getString("Frekans"),
                                 rs.getString("Ton"),
                                 rs.getString("Squelch")
                                );
                usersList.add(user);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
     public void findUsers()
    {
        ArrayList<kullanıcılar_class> users = ListUsers(jText_Search.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"İl","Yer","Yükseklik","Güç","Band","Frekans","Ton","Squelch"});
        Object[] row = new Object[8];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getİl();
            row[1] = users.get(i).getYer();
            row[2] = users.get(i).getYükseklik();
            row[3] = users.get(i).getGüç();
            row[4] = users.get(i).getBand();
            row[5] = users.get(i).getFrekans();
            row[6] = users.get(i).getTon();
            row[7] = users.get(i).getSquelch();
            model.addRow(row);
        }
       jTable_Users.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        jText_Search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aprs_radio = new javax.swing.JRadioButton();
        uhf_radio = new javax.swing.JRadioButton();
        vhf_radio = new javax.swing.JRadioButton();
        dmr_radio = new javax.swing.JRadioButton();
        echo_radio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tümü_radio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Users);

        jText_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_SearchKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(231, 76, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Türkiye Amatör Telsiz Röle Listesi");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unnamed.png"))); // NOI18N
        jLabel2.setText("Anamenü");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("İl Ara :");

        aprs_radio.setBackground(new java.awt.Color(52, 152, 219));
        aprs_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aprs_radio.setForeground(new java.awt.Color(255, 255, 255));
        aprs_radio.setText("APRS");
        aprs_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aprs_radioİtemStateChanged(evt);
            }
        });

        uhf_radio.setBackground(new java.awt.Color(52, 152, 219));
        uhf_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uhf_radio.setForeground(new java.awt.Color(255, 255, 255));
        uhf_radio.setText("UHF");
        uhf_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                uhf_radioİtemStateChanged(evt);
            }
        });

        vhf_radio.setBackground(new java.awt.Color(52, 152, 219));
        vhf_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vhf_radio.setForeground(new java.awt.Color(255, 255, 255));
        vhf_radio.setText("VHF");
        vhf_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vhf_radioİtemStateChanged(evt);
            }
        });

        dmr_radio.setBackground(new java.awt.Color(52, 152, 219));
        dmr_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dmr_radio.setForeground(new java.awt.Color(255, 255, 255));
        dmr_radio.setText("DMR");
        dmr_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dmr_radioİtemStateChanged(evt);
            }
        });

        echo_radio.setBackground(new java.awt.Color(52, 152, 219));
        echo_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        echo_radio.setForeground(new java.awt.Color(255, 255, 255));
        echo_radio.setText("EchoLink");
        echo_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                echo_radioİtemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Band Filtresi :");

        tümü_radio.setBackground(new java.awt.Color(52, 152, 219));
        tümü_radio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tümü_radio.setForeground(new java.awt.Color(255, 255, 255));
        tümü_radio.setText("Tümü");
        tümü_radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tümü_radioİtemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Röle Bilgileri ta2kb.com Üzerinden Alınmıştır. Teşekkürler");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(292, 292, 292)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tümü_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aprs_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uhf_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vhf_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dmr_radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(echo_radio)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(aprs_radio)
                    .addComponent(uhf_radio)
                    .addComponent(vhf_radio)
                    .addComponent(dmr_radio)
                    .addComponent(echo_radio)
                    .addComponent(jLabel4)
                    .addComponent(tümü_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      dispose();
        menu u1 =new menu();
        menu.operator_ismi.setText(giris.jTextField_Username.getText());
        u1.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jText_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_SearchKeyReleased
       findUsers();
    }//GEN-LAST:event_jText_SearchKeyReleased

    private void aprs_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aprs_radioİtemStateChanged
    //String query=getSelected();
    //filter(query);
      
    }//GEN-LAST:event_aprs_radioİtemStateChanged

    private void uhf_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_uhf_radioİtemStateChanged
    //  String query=getSelected();
      //filter(query);
    }//GEN-LAST:event_uhf_radioİtemStateChanged

    private void vhf_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vhf_radioİtemStateChanged
       // String query=getSelected();
        //filter(query);
    }//GEN-LAST:event_vhf_radioİtemStateChanged

    private void dmr_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dmr_radioİtemStateChanged
        //String query=getSelected();
        //filter(query);
    }//GEN-LAST:event_dmr_radioİtemStateChanged

    private void echo_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_echo_radioİtemStateChanged
        //String query=getSelected();
        //filter(query);
    }//GEN-LAST:event_echo_radioİtemStateChanged

    private void tümü_radioİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tümü_radioİtemStateChanged
        //String query=getSelected();
        //filter(query);
    }//GEN-LAST:event_tümü_radioİtemStateChanged

    ///Fılter
   // private void filter(String query)
    //{
      // DefaultTableModel dm = (null);
       // TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel> (dm);
        //jTable_Users.setRowSorter(tr);
        
        //Check Fılter Query
       // if(query != "Band")
        //{
         //   tr.setRowFilter(RowFilter.regexFilter(query));
        //}else
        //{
         //   jTable_Users.setRowSorter(tr);
        //}
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(role_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(role_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(role_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(role_listesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new role_listesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aprs_radio;
    private javax.swing.JRadioButton dmr_radio;
    private javax.swing.JRadioButton echo_radio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JRadioButton tümü_radio;
    private javax.swing.JRadioButton uhf_radio;
    private javax.swing.JRadioButton vhf_radio;
    // End of variables declaration//GEN-END:variables
}
